# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html

security:
    encoders:
        WTI\HelloBundle\Entity\User:
            algorithm: bcrypt
            cost: 13

    providers:
        wti_user_db_provider:
            entity:
                class: WTI\HelloBundle\Entity\User
                property: email

    firewalls:
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: '^/login', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/register', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/post/', roles: ROLE_USER }

    # disables authentication for assets and the profiler, adapt it according to your needs
    #dev:
    #    pattern: ^/(_(profiler|wdt)|css|images|js)/
    #    security: false
